-- This migration is a baseline sync.
-- The database already contains these changes (applied previously), so we mark it as applied.

ALTER TABLE `KpiPlan` ADD COLUMN `confirmRequestedAt` DATETIME(3) NULL;

ALTER TABLE `Notification` MODIFY `type` ENUM(
  'EVALUATEE_REQUEST_EVALUATOR_APPROVE_KPI',
  'EVALUATEE_CONFIRM_EVALUATOR_KPI',
  'EVALUATEE_REJECT_EVALUATOR_KPI',
  'EVALUATOR_REQUEST_EVALUATEE_CONFIRM_KPI',
  'EVALUATOR_REQUEST_EVALUATEE_DEFINE_KPI',
  'EVALUATOR_APPROVE_EVALUATEE_KPI',
  'EVALUATOR_REJECT_EVALUATEE_KPI',
  'EVALUATOR_CANCEL_REQUEST_EVALUATEE_CONFIRM_KPI'
) NOT NULL;
