/*
  Warnings:

  - The values [KPI_ASSIGNED,KPI_SUBMITTED,KPI_REVISED,KPI_APPROVED,KPI_REJECTED,EVALUATION_SUBMITTED,EVALUATION_COMPLETED] on the enum `Notification_type` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('EVALUATEE_REQUEST_EVALUATOR_APPROVE_KPI', 'EVALUATEE_CONFIRM_EVALUATOR_KPI', 'EVALUATEE_REJECT_EVALUATOR_KPI', 'EVALUATOR_REQUEST_EVALUATEE_CONFIRM_KPI', 'EVALUATOR_REQUEST_EVALUATEE_DEFINE_KPI', 'EVALUATOR_APPROVE_EVALUATEE_KPI', 'EVALUATOR_REJECT_EVALUATEE_KPI') NOT NULL;
