-- AlterTable
ALTER TABLE `EvaluationCycle` ADD COLUMN `kpiDefineMode` ENUM('EVALUATOR_DEFINES_EVALUATEE_CONFIRMS', 'EVALUATEE_DEFINES_EVALUATOR_APPROVES') NOT NULL DEFAULT 'EVALUATOR_DEFINES_EVALUATEE_CONFIRMS';
